# Generated by Django 4.2.5 on 2023-10-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0003_patient_rename_checkup_symptom_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='lastname',
        ),
        migrations.AddField(
            model_name='symptom',
            name='symptom',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
