# Generated by Django 4.2.5 on 2023-10-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0004_remove_symptom_firstname_remove_symptom_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthApp.symptom')),
            ],
        ),
    ]
