# Generated by Django 4.2.5 on 2023-10-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0005_treatment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treatment',
            old_name='description',
            new_name='possible_diseases',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='name',
        ),
        migrations.AddField(
            model_name='treatment',
            name='treatment',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
