# Generated by Django 4.2.5 on 2023-10-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthApp', '0007_remove_treatment_possible_diseases'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='possible_diseases',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
